FROM golang:1.18 as builder
WORKDIR /app
COPY . .
RUN cd client && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../bin/client

FROM scratch as runner
COPY --from=builder /app/bin/client /client
ENTRYPOINT [ "./client" ]
