// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Crypto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Up                   int64    `protobuf:"varint,3,opt,name=up,proto3" json:"up,omitempty"`
	Down                 int64    `protobuf:"varint,4,opt,name=down,proto3" json:"down,omitempty"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crypto) Reset()         { *m = Crypto{} }
func (m *Crypto) String() string { return proto.CompactTextString(m) }
func (*Crypto) ProtoMessage()    {}
func (*Crypto) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

func (m *Crypto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crypto.Unmarshal(m, b)
}
func (m *Crypto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crypto.Marshal(b, m, deterministic)
}
func (m *Crypto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crypto.Merge(m, src)
}
func (m *Crypto) XXX_Size() int {
	return xxx_messageInfo_Crypto.Size(m)
}
func (m *Crypto) XXX_DiscardUnknown() {
	xxx_messageInfo_Crypto.DiscardUnknown(m)
}

var xxx_messageInfo_Crypto proto.InternalMessageInfo

func (m *Crypto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Crypto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Crypto) GetUp() int64 {
	if m != nil {
		return m.Up
	}
	return 0
}

func (m *Crypto) GetDown() int64 {
	if m != nil {
		return m.Down
	}
	return 0
}

func (m *Crypto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateCryptoResponse struct {
	Crypto               *Crypto  `protobuf:"bytes,1,opt,name=crypto,proto3" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCryptoResponse) Reset()         { *m = CreateCryptoResponse{} }
func (m *CreateCryptoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCryptoResponse) ProtoMessage()    {}
func (*CreateCryptoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{1}
}

func (m *CreateCryptoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCryptoResponse.Unmarshal(m, b)
}
func (m *CreateCryptoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCryptoResponse.Marshal(b, m, deterministic)
}
func (m *CreateCryptoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCryptoResponse.Merge(m, src)
}
func (m *CreateCryptoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCryptoResponse.Size(m)
}
func (m *CreateCryptoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCryptoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCryptoResponse proto.InternalMessageInfo

func (m *CreateCryptoResponse) GetCrypto() *Crypto {
	if m != nil {
		return m.Crypto
	}
	return nil
}

type UpvoteCryptoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpvoteCryptoRequest) Reset()         { *m = UpvoteCryptoRequest{} }
func (m *UpvoteCryptoRequest) String() string { return proto.CompactTextString(m) }
func (*UpvoteCryptoRequest) ProtoMessage()    {}
func (*UpvoteCryptoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{2}
}

func (m *UpvoteCryptoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpvoteCryptoRequest.Unmarshal(m, b)
}
func (m *UpvoteCryptoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpvoteCryptoRequest.Marshal(b, m, deterministic)
}
func (m *UpvoteCryptoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpvoteCryptoRequest.Merge(m, src)
}
func (m *UpvoteCryptoRequest) XXX_Size() int {
	return xxx_messageInfo_UpvoteCryptoRequest.Size(m)
}
func (m *UpvoteCryptoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpvoteCryptoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpvoteCryptoRequest proto.InternalMessageInfo

func (m *UpvoteCryptoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpvoteCryptoResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpvoteCryptoResponse) Reset()         { *m = UpvoteCryptoResponse{} }
func (m *UpvoteCryptoResponse) String() string { return proto.CompactTextString(m) }
func (*UpvoteCryptoResponse) ProtoMessage()    {}
func (*UpvoteCryptoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{3}
}

func (m *UpvoteCryptoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpvoteCryptoResponse.Unmarshal(m, b)
}
func (m *UpvoteCryptoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpvoteCryptoResponse.Marshal(b, m, deterministic)
}
func (m *UpvoteCryptoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpvoteCryptoResponse.Merge(m, src)
}
func (m *UpvoteCryptoResponse) XXX_Size() int {
	return xxx_messageInfo_UpvoteCryptoResponse.Size(m)
}
func (m *UpvoteCryptoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpvoteCryptoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpvoteCryptoResponse proto.InternalMessageInfo

func (m *UpvoteCryptoResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DownvoteCryptoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownvoteCryptoRequest) Reset()         { *m = DownvoteCryptoRequest{} }
func (m *DownvoteCryptoRequest) String() string { return proto.CompactTextString(m) }
func (*DownvoteCryptoRequest) ProtoMessage()    {}
func (*DownvoteCryptoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{4}
}

func (m *DownvoteCryptoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownvoteCryptoRequest.Unmarshal(m, b)
}
func (m *DownvoteCryptoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownvoteCryptoRequest.Marshal(b, m, deterministic)
}
func (m *DownvoteCryptoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownvoteCryptoRequest.Merge(m, src)
}
func (m *DownvoteCryptoRequest) XXX_Size() int {
	return xxx_messageInfo_DownvoteCryptoRequest.Size(m)
}
func (m *DownvoteCryptoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownvoteCryptoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownvoteCryptoRequest proto.InternalMessageInfo

func (m *DownvoteCryptoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DownvoteCryptoResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownvoteCryptoResponse) Reset()         { *m = DownvoteCryptoResponse{} }
func (m *DownvoteCryptoResponse) String() string { return proto.CompactTextString(m) }
func (*DownvoteCryptoResponse) ProtoMessage()    {}
func (*DownvoteCryptoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{5}
}

func (m *DownvoteCryptoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownvoteCryptoResponse.Unmarshal(m, b)
}
func (m *DownvoteCryptoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownvoteCryptoResponse.Marshal(b, m, deterministic)
}
func (m *DownvoteCryptoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownvoteCryptoResponse.Merge(m, src)
}
func (m *DownvoteCryptoResponse) XXX_Size() int {
	return xxx_messageInfo_DownvoteCryptoResponse.Size(m)
}
func (m *DownvoteCryptoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownvoteCryptoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownvoteCryptoResponse proto.InternalMessageInfo

func (m *DownvoteCryptoResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetCryptoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCryptoRequest) Reset()         { *m = GetCryptoRequest{} }
func (m *GetCryptoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCryptoRequest) ProtoMessage()    {}
func (*GetCryptoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{6}
}

func (m *GetCryptoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCryptoRequest.Unmarshal(m, b)
}
func (m *GetCryptoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCryptoRequest.Marshal(b, m, deterministic)
}
func (m *GetCryptoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCryptoRequest.Merge(m, src)
}
func (m *GetCryptoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCryptoRequest.Size(m)
}
func (m *GetCryptoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCryptoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCryptoRequest proto.InternalMessageInfo

func (m *GetCryptoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCryptoResponse struct {
	Crypto               *Crypto  `protobuf:"bytes,1,opt,name=crypto,proto3" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCryptoResponse) Reset()         { *m = GetCryptoResponse{} }
func (m *GetCryptoResponse) String() string { return proto.CompactTextString(m) }
func (*GetCryptoResponse) ProtoMessage()    {}
func (*GetCryptoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{7}
}

func (m *GetCryptoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCryptoResponse.Unmarshal(m, b)
}
func (m *GetCryptoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCryptoResponse.Marshal(b, m, deterministic)
}
func (m *GetCryptoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCryptoResponse.Merge(m, src)
}
func (m *GetCryptoResponse) XXX_Size() int {
	return xxx_messageInfo_GetCryptoResponse.Size(m)
}
func (m *GetCryptoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCryptoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCryptoResponse proto.InternalMessageInfo

func (m *GetCryptoResponse) GetCrypto() *Crypto {
	if m != nil {
		return m.Crypto
	}
	return nil
}

type GetAllCryptosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllCryptosRequest) Reset()         { *m = GetAllCryptosRequest{} }
func (m *GetAllCryptosRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllCryptosRequest) ProtoMessage()    {}
func (*GetAllCryptosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{8}
}

func (m *GetAllCryptosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCryptosRequest.Unmarshal(m, b)
}
func (m *GetAllCryptosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCryptosRequest.Marshal(b, m, deterministic)
}
func (m *GetAllCryptosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCryptosRequest.Merge(m, src)
}
func (m *GetAllCryptosRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllCryptosRequest.Size(m)
}
func (m *GetAllCryptosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCryptosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCryptosRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Crypto)(nil), "Crypto")
	proto.RegisterType((*CreateCryptoResponse)(nil), "CreateCryptoResponse")
	proto.RegisterType((*UpvoteCryptoRequest)(nil), "UpvoteCryptoRequest")
	proto.RegisterType((*UpvoteCryptoResponse)(nil), "UpvoteCryptoResponse")
	proto.RegisterType((*DownvoteCryptoRequest)(nil), "DownvoteCryptoRequest")
	proto.RegisterType((*DownvoteCryptoResponse)(nil), "DownvoteCryptoResponse")
	proto.RegisterType((*GetCryptoRequest)(nil), "GetCryptoRequest")
	proto.RegisterType((*GetCryptoResponse)(nil), "GetCryptoResponse")
	proto.RegisterType((*GetAllCryptosRequest)(nil), "GetAllCryptosRequest")
}

func init() { proto.RegisterFile("crypto.proto", fileDescriptor_527278fb02d03321) }

var fileDescriptor_527278fb02d03321 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xd3, 0xe5, 0xcf, 0xfb, 0x32, 0x22, 0x91, 0xa1, 0xc5, 0xa6, 0x17, 0xc9, 0x26, 0x2a,
	0xa7, 0x8d, 0xa2, 0x89, 0x07, 0x4f, 0x88, 0x09, 0xf7, 0x1a, 0x3d, 0x78, 0x03, 0xba, 0x9a, 0x86,
	0xda, 0x5d, 0xdb, 0x2d, 0xc4, 0xef, 0xe4, 0x87, 0x34, 0x6c, 0x8b, 0xb6, 0xb5, 0xa8, 0xb7, 0x99,
	0x27, 0xcf, 0x3e, 0x33, 0xf3, 0xcb, 0x42, 0x7b, 0x11, 0xbd, 0x49, 0x25, 0x98, 0x8c, 0x84, 0x12,
	0xf4, 0x09, 0x9a, 0x13, 0xdd, 0x63, 0x07, 0x88, 0xef, 0xd9, 0xc6, 0xc0, 0x18, 0xb6, 0x5c, 0xe2,
	0x7b, 0x88, 0x50, 0x0f, 0x67, 0x2f, 0xdc, 0x26, 0x5a, 0xd1, 0xf5, 0xc6, 0x93, 0x48, 0xbb, 0x36,
	0x30, 0x86, 0x35, 0x97, 0x24, 0x72, 0xe3, 0xf1, 0xc4, 0x3a, 0xb4, 0xeb, 0x5a, 0xd1, 0x35, 0x9a,
	0xd0, 0x50, 0x42, 0xcd, 0x02, 0xbb, 0xa1, 0xc5, 0xb4, 0xa1, 0x57, 0x60, 0x4e, 0x22, 0x3e, 0x53,
	0x3c, 0x9d, 0xe6, 0xf2, 0x58, 0x8a, 0x30, 0xe6, 0x78, 0x04, 0xcd, 0x74, 0x1f, 0x3d, 0x79, 0x6f,
	0xf4, 0x8f, 0x65, 0x86, 0x4c, 0xa6, 0xc7, 0xd0, 0xbb, 0x97, 0x2b, 0xf1, 0xf5, 0xf0, 0x35, 0xe1,
	0xb1, 0x2a, 0x6f, 0x4b, 0x4f, 0xc0, 0x2c, 0xda, 0xb2, 0xfc, 0x0e, 0x10, 0xb1, 0xd4, 0xbe, 0xff,
	0x2e, 0x11, 0x4b, 0x7a, 0x0a, 0xd6, 0xad, 0x58, 0x87, 0xbf, 0x07, 0x0e, 0xa1, 0x5f, 0x36, 0xee,
	0x88, 0xa4, 0x70, 0x30, 0xe5, 0xea, 0xe7, 0xb4, 0x4b, 0xe8, 0xe6, 0x3c, 0x7f, 0xbd, 0xbd, 0x0f,
	0xe6, 0x94, 0xab, 0x71, 0x10, 0xa4, 0x7a, 0x9c, 0xa5, 0x8f, 0xde, 0x09, 0xf4, 0x52, 0xe9, 0x41,
	0x28, 0x3f, 0x7c, 0xbe, 0xe3, 0xd1, 0xca, 0x5f, 0x70, 0x64, 0xd0, 0xce, 0x43, 0xc6, 0x6d, 0xa0,
	0x63, 0xb1, 0x4a, 0xf8, 0xd7, 0xd0, 0xce, 0x43, 0x43, 0x93, 0x55, 0xa0, 0x76, 0x2c, 0x56, 0x49,
	0x76, 0x0c, 0x9d, 0x22, 0x20, 0xec, 0xb3, 0x4a, 0xb4, 0xce, 0x21, 0xdb, 0x41, 0x72, 0x04, 0xad,
	0x4f, 0x2a, 0xd8, 0x65, 0x65, 0x8a, 0x0e, 0xb2, 0xef, 0xd0, 0xce, 0x61, 0xbf, 0xc0, 0x04, 0x2d,
	0x56, 0xc5, 0xc8, 0xd9, 0xde, 0x7e, 0x66, 0xdc, 0xd4, 0x1f, 0x89, 0x9c, 0xcf, 0x9b, 0xfa, 0xc3,
	0x5f, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0x74, 0xad, 0x89, 0xac, 0x00, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CryptoVotingServiceClient is the client API for CryptoVotingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CryptoVotingServiceClient interface {
	CreateCrypto(ctx context.Context, in *Crypto, opts ...grpc.CallOption) (*CreateCryptoResponse, error)
	UpvoteCrypto(ctx context.Context, in *UpvoteCryptoRequest, opts ...grpc.CallOption) (*UpvoteCryptoResponse, error)
	DownvoteCrypto(ctx context.Context, in *DownvoteCryptoRequest, opts ...grpc.CallOption) (*DownvoteCryptoResponse, error)
	GetCrypto(ctx context.Context, in *GetCryptoRequest, opts ...grpc.CallOption) (*GetCryptoResponse, error)
	GetAllCryptos(ctx context.Context, in *GetAllCryptosRequest, opts ...grpc.CallOption) (CryptoVotingService_GetAllCryptosClient, error)
}

type cryptoVotingServiceClient struct {
	cc *grpc.ClientConn
}

func NewCryptoVotingServiceClient(cc *grpc.ClientConn) CryptoVotingServiceClient {
	return &cryptoVotingServiceClient{cc}
}

func (c *cryptoVotingServiceClient) CreateCrypto(ctx context.Context, in *Crypto, opts ...grpc.CallOption) (*CreateCryptoResponse, error) {
	out := new(CreateCryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoVotingService/CreateCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoVotingServiceClient) UpvoteCrypto(ctx context.Context, in *UpvoteCryptoRequest, opts ...grpc.CallOption) (*UpvoteCryptoResponse, error) {
	out := new(UpvoteCryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoVotingService/UpvoteCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoVotingServiceClient) DownvoteCrypto(ctx context.Context, in *DownvoteCryptoRequest, opts ...grpc.CallOption) (*DownvoteCryptoResponse, error) {
	out := new(DownvoteCryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoVotingService/DownvoteCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoVotingServiceClient) GetCrypto(ctx context.Context, in *GetCryptoRequest, opts ...grpc.CallOption) (*GetCryptoResponse, error) {
	out := new(GetCryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoVotingService/GetCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoVotingServiceClient) GetAllCryptos(ctx context.Context, in *GetAllCryptosRequest, opts ...grpc.CallOption) (CryptoVotingService_GetAllCryptosClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CryptoVotingService_serviceDesc.Streams[0], "/CryptoVotingService/GetAllCryptos", opts...)
	if err != nil {
		return nil, err
	}
	x := &cryptoVotingServiceGetAllCryptosClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CryptoVotingService_GetAllCryptosClient interface {
	Recv() (*Crypto, error)
	grpc.ClientStream
}

type cryptoVotingServiceGetAllCryptosClient struct {
	grpc.ClientStream
}

func (x *cryptoVotingServiceGetAllCryptosClient) Recv() (*Crypto, error) {
	m := new(Crypto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CryptoVotingServiceServer is the server API for CryptoVotingService service.
type CryptoVotingServiceServer interface {
	CreateCrypto(context.Context, *Crypto) (*CreateCryptoResponse, error)
	UpvoteCrypto(context.Context, *UpvoteCryptoRequest) (*UpvoteCryptoResponse, error)
	DownvoteCrypto(context.Context, *DownvoteCryptoRequest) (*DownvoteCryptoResponse, error)
	GetCrypto(context.Context, *GetCryptoRequest) (*GetCryptoResponse, error)
	GetAllCryptos(*GetAllCryptosRequest, CryptoVotingService_GetAllCryptosServer) error
}

// UnimplementedCryptoVotingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCryptoVotingServiceServer struct {
}

func (*UnimplementedCryptoVotingServiceServer) CreateCrypto(ctx context.Context, req *Crypto) (*CreateCryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCrypto not implemented")
}
func (*UnimplementedCryptoVotingServiceServer) UpvoteCrypto(ctx context.Context, req *UpvoteCryptoRequest) (*UpvoteCryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpvoteCrypto not implemented")
}
func (*UnimplementedCryptoVotingServiceServer) DownvoteCrypto(ctx context.Context, req *DownvoteCryptoRequest) (*DownvoteCryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownvoteCrypto not implemented")
}
func (*UnimplementedCryptoVotingServiceServer) GetCrypto(ctx context.Context, req *GetCryptoRequest) (*GetCryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrypto not implemented")
}
func (*UnimplementedCryptoVotingServiceServer) GetAllCryptos(req *GetAllCryptosRequest, srv CryptoVotingService_GetAllCryptosServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllCryptos not implemented")
}

func RegisterCryptoVotingServiceServer(s *grpc.Server, srv CryptoVotingServiceServer) {
	s.RegisterService(&_CryptoVotingService_serviceDesc, srv)
}

func _CryptoVotingService_CreateCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Crypto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoVotingServiceServer).CreateCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoVotingService/CreateCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoVotingServiceServer).CreateCrypto(ctx, req.(*Crypto))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoVotingService_UpvoteCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpvoteCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoVotingServiceServer).UpvoteCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoVotingService/UpvoteCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoVotingServiceServer).UpvoteCrypto(ctx, req.(*UpvoteCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoVotingService_DownvoteCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownvoteCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoVotingServiceServer).DownvoteCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoVotingService/DownvoteCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoVotingServiceServer).DownvoteCrypto(ctx, req.(*DownvoteCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoVotingService_GetCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoVotingServiceServer).GetCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoVotingService/GetCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoVotingServiceServer).GetCrypto(ctx, req.(*GetCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoVotingService_GetAllCryptos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllCryptosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CryptoVotingServiceServer).GetAllCryptos(m, &cryptoVotingServiceGetAllCryptosServer{stream})
}

type CryptoVotingService_GetAllCryptosServer interface {
	Send(*Crypto) error
	grpc.ServerStream
}

type cryptoVotingServiceGetAllCryptosServer struct {
	grpc.ServerStream
}

func (x *cryptoVotingServiceGetAllCryptosServer) Send(m *Crypto) error {
	return x.ServerStream.SendMsg(m)
}

var _CryptoVotingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CryptoVotingService",
	HandlerType: (*CryptoVotingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCrypto",
			Handler:    _CryptoVotingService_CreateCrypto_Handler,
		},
		{
			MethodName: "UpvoteCrypto",
			Handler:    _CryptoVotingService_UpvoteCrypto_Handler,
		},
		{
			MethodName: "DownvoteCrypto",
			Handler:    _CryptoVotingService_DownvoteCrypto_Handler,
		},
		{
			MethodName: "GetCrypto",
			Handler:    _CryptoVotingService_GetCrypto_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllCryptos",
			Handler:       _CryptoVotingService_GetAllCryptos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crypto.proto",
}
